[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]
cacheDirectories = ["node_modules", ".turbo", "dist"]

[start]
cmd = "npm run start:prod"
